language: node_js
node_js:
  - 10
cache: npm

notifications:
  slack:
    secure: v27mKyJkfKI4b6uYDYE404A84bmZ7s+zUjBQg2zx71BJht9G4AAmBQegYSACCtroN28f75LnVwV4Xz8g19bKSWihwi6Gff4Z3RkdLnqrjjVxVxgk1x/AIL4/2DGh2PkHo3Y7cN41lFKXus9dOSr3lDGE/0AlfO+H14Qn3tkhCe6fAJTSl7oDcrQ91VptcTK3YnVa0YbNgBX18ypQqg5RSc2P8N9Drg6BPS0IqM38hrR2FyM27L5rAmnkCF9pey9o6s5djQM/8RumLZ6JVkI3U2Iq/Sf6d1J3M1CnEZ1N7ob8KCCeGqts2fEb+iSTnqtwAb+uxGmXQSpIxiU0RJj4RH4q1z0CwSyXr2NFV++lhM0qrLP2MHzy788XfXNx+VT9qzWhoO5VnN5+gJLL6OZpMJRK5xlyxExNMPhaA5AcpUhtQ9TsKgdacRe3hRDr4yfVw9GsILU8zv5iqbkINPVo2ozQp52n0qlDgte+EfiRxdfJFDKA5c5xPOaE3IPH6H24gzVZl9q9QrI0eseZ8T4o/2uKyyCNDtuYtYroGD+OPC7I6vZrZOb95QXkuHN9TCqLIUgpT/dZl0ZgFfOTbgX/w5wrXWrOm2mho0q9Miu/7KPvwirIxrIAwE8SiPq67rWJ5OfGrpog3Tz8/3HoO9GGDYZfe4NGZjLMxbmQt4fFiFo=

script:
  - npm run-script build
  - npm run-script test

after_success:
  - npm run-script lint
  - if [[ ("$TRAVIS_BRANCH" != "master" && "$TRAVIS_BRANCH" != "release") || ("$TRAVIS_PULL_REQUEST" != "false" && "$TRAVIS_BRANCH" = "master") ]] ; then bash <(curl -s https://codecov.io/bash) ; fi
  - ./scripts/post-build.sh