language: node_js
node_js:
  - 10
cache: npm

notifications:
  slack:
    secure: RKdzA1G23oIADnjAGfPsJEonG/lR1mZxORDcISmDuk8SDagLcNua3p2MYMgxJtcTdTCF0qTow85kr51lfyNCfbPYA8dSBXLbBcihOVNMmoCUoWUzpOgcAIg3cAF6eTc4k6yhkJ6uC11OZdy9PZWlUcp+ZGOjPRoHejaw0MifQnkjyPis1XDMBQVd1A7pJ0Rqdcv6e1qvv+UxVxYXpJ2ip3BNTIvRejG3+oXx29b2EFDlNnzHPOsD/6BVykqTlR+4bo+T/yazdfRhEFeTOM4z7eZyF2kUvNA7vzVuW+lt5THUrafXj62KXz0E+5Y7QRCG1mRxlV+ZxF5HMLt19OyDcIwfDCoMIHsiOd+QiLt6g9pN+xyF1PyBpmRnyDAoSVN5vDgpLJNxmgB5V4Uc6qpDk5UI85jPErmfpe6LNkrWlsGz8NJCaScsg9nLrf32bNxHqXhnx8GZ+Rp9U3SYVylWveYID9txxT33BAuz3QbJatDPPcNpIoWgBcsVH+4yF3KPMYjrjQONMZeuwUsmBwi9POqS87f8q4oWzuqyaRKHwufsyVVfztorgM4Xgp9YxB2+l0i4rY74KeIR9v0HPf1p+FIv4TsCtW8e3XK2g9RQ7PCWg6yZM7QDLMV/IF6RruolRQpcddyf0D7Xfse3FGxnI7o+SspBB/nBVSa67e4mVaU=

script:
  - npm run-script build
  - npm run-script test

after_success:
  - npm run-script lint
  - if [[ ("$TRAVIS_BRANCH" != "master" && "$TRAVIS_BRANCH" != "release") || ("$TRAVIS_PULL_REQUEST" != "false" && "$TRAVIS_BRANCH" = "master") ]] ; then bash <(curl -s https://codecov.io/bash) ; fi
  - ./scripts/post-build.sh